# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Demarko Fulcher
title: Student / Student Coordinator 
email: demarko.fulchersb@gmail.com
website: https://demarkolfulcher.github.io/

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: facespics
github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: jameswgrant
linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Meteorological Modeling in the Baltimore/ Washington Region
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.
          
      - layout: top-middle
        title: Apartment Rent Rent Price Prediction on Synthetic Data
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app.

      - layout: top-middle
        title: Credit Card Fraud Detection on Unbalance and Unlabelled Data
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app.

  - title: Experience  # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Building STEPS
        caption: 7/2022 - 8/2022
        sub_title: General Tutor
        quote: >
          Developed by a science consultant to help under-represented students become science and technology professionals, Building STEPS increases the number of students who earn a college degree and enter STEM and healthcare careers. Launched in Baltimore in 2000, and partnering with our city’s more challenged, under-resourced public high schools, Building STEPS unlocks potential and propels high achieving, highly motivated students to college and career success.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.
      - layout: left
        title: AI4ALL
        caption: 7/2024 - 9/2024
        sub_title: Student Coordinator
        quote: >
          AI4ALL is a US-based nonprofit dedicated to increasing diversity and inclusion in AI education, research, development, and policy. As of December 2022, AI4ALL has impacted over 10,000 people in all 50 states and around the world through our programs.
        description: | # this will include new lines to allow paragraphs
          I have experience facilitating and assisting with AI4ALL Ignite Career Readiness events, specifically in conducting Resume and LinkedIn reviews, as well as participating in Opportunity Chats aimed at recruitment. I regularly held periodic check-in meetings with staff and fellow student coordinators to ensure smooth coordination and communication throughout programs. Additionally, I actively participated in debriefing meetings following the conclusion of AI4ALL Ignite Career Readiness programs to evaluate outcomes and identify areas for improvement. I provided administrative support for 2-3 AI4ALL Ignite Career Readiness classes, which included managing student communications, documenting assignments, and tracking attendance. I also gained proficiency in Salesforce by documenting student internship experiences across various AI4ALL programs. Furthermore, I effectively managed projects and tasks using the Asana work management platform, demonstrating strong organizational skills and attention to detail in project execution.


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Maryland Baltimore County
        caption: 2020 - 2025
        sub_title: B.A. Matematics and Statistics 
        quote: >
          The University of Maryland, Baltimore County (UMBC), founded in 1966, is a public research university located in Baltimore County, Maryland. It was established as part of the University System of Maryland and has since grown into a prominent institution known for its excellence in education and research.
        description: | # this will include new lines to allow paragraphs
          During my pursuit of dual degrees in Mathematics and Computer Science at the University of Maryland Baltimore County, I acquired essential skills that have significantly shaped my career, particularly in teamwork and meeting stringent deadlines. My university experience was enriching, providing me with insights into maintaining a balanced work-life dynamic. Outside of academics, I dedicated a substantial portion of my free time to serving on the committees of various clubs, including roles such as Event Coordinator and Treasurer at the UMBC Astronomy Club. These experiences were instrumental in honing my leadership and financial management abilities.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
