# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: "Demarko Fulcher"
title: "Student / Student Coordinator"
email: demarko.fulchersb@gmail.com
website: "https://demarkolfulcher.github.io/"

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: facespics
github_username: sproogen
instagram_username: jameswgrant
linkedin_username: jameswgrant
youtube_username: globalmtb

# Additional icon links
additional_links:
  - title: "itsgoingto.be"
    icon: "fas fa-globe"
    url: "https://www.itsgoingto.be"

# About Section
about_profile_image: images/profile.jpg
about_content: |
  Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

# Content sections
content:
  - title: "Projects"
    layout: list
    content:
      - layout: top-middle
        title: "Meteorological Modeling in the Baltimore/ Washington Region"
        link: "github.com/sproogen"
        additional_links:
          - title: "sproogen/modern-resume-theme"
            icon: "fab fa-github"
            url: "github.com/sproogen/modern-resume-theme"
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: |
          I started this project as a way of learning <mark>React</mark> and it has since grown into a fully fledged app.

      - layout: top-middle
        title: "Apartment Rent Price Prediction on Synthetic Data"
        link: "github.com/sproogen"
        additional_links:
          - title: "sproogen/modern-resume-theme"
            icon: "fab fa-github"
            url: "github.com/sproogen/modern-resume-theme"
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: |
          I started this project as a way of learning <mark>React</mark> and it has since grown into a fully fledged app.

      - layout: top-middle
        title: "Credit Card Fraud Detection on Unbalanced and Unlabeled Data"
        link: "github.com/sproogen"
        additional_links:
          - title: "sproogen/modern-resume-theme"
            icon: "fab fa-github"
            url: "github.com/sproogen/modern-resume-theme"
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: |
          I started this project as a way of learning <mark>React</mark> and it has since grown into a fully fledged app.

  - title: "Experience"
    layout: list
    content:
      - layout: left
        title: "AI4ALL"
        link: "https://ai4allchangemakers.org/home"
        sub_title: "Student Coordinator"
        caption: "July 2024 - Present"
        quote: >
          Solving 21st-century problems by digging holes and making game-changing products like the *not a flamethrower*.
        description: |
          Every company needs its networks properly administered and The Boring Company is no exception. Digging holes is hard, and I play my part in making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

      - layout: left
        title: "Building STEPS"
        link: "https://www.buildingsteps.org/"
        sub_title: "General Tutor"
        caption: "July 2022 - August 2022"
        quote: >
          Solving 21st-century problems by digging holes and making game-changing products like the *not a flamethrower*.
        description: |
          Every company needs its networks properly administered and The Boring Company is no exception. Digging holes is hard, and I play my part in making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: "Education"
    layout: list
    content:
      - layout: left
        title: "Harvard University"
        caption: "2020 - 2025"
        sub_title: "B.A. Mathematics"
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: |
          During my time at Harvard, I learned most of my key skills that I have taken through my career, such as teamwork and working to tight deadlines. I thoroughly enjoyed my time at university and learned a lot about a healthy work-life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: "A Little More About Me"
    layout: text
    content: |
      Alongside my interests in networks and software engineering, some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true
