# Site
repository: sproogen/resume-theme
favicon: images/fat_penguin.jpeg

# Content configuration version
version: 2

# Personal info
name: Demarko Fulcher
title: Computer Science Masters Student / Cyber Security Researcher 
email: demarko.fulchersb@gmail.com
School email: demarkf1@umbc.edu
website: https://demarkolfulcher.github.io/

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: 
github_username:  demarkoLfulcher
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: 
linkedin_username: 
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: demarkolfulcher.github.io
  icon: fas fa-globe
  url: https://demarkolfulcher.github.io/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_content: | # this will include new lines to allow paragraphs
  I'm a highly motivated senior in Mathematics with a Computer Science and Statistics minors, possessing a robust academic background within high level Mathematics, Statistics and Computer Science Theory. I’m currently completing an independent study on Cellular Automata under the guidance of Professor Richard Chang. I hope to continue my journey in Mathematics and Statistics such that I can apply my mathematical knowledge into Computer Science Theory and Applications.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Post - Quantum Symmetric Key Agreement 
        link: github.com/demarkoLfulcher
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
             Analyzed post-quantum symmetric key agreement protocols for resilience to quantum attacks. Identified limitations in scalability and security, collaborated on feasibility assessments. Initiated plans for a novel protocol to enhance speed, security, and scalability.      
      - layout: top-middle
        title: SFS Winter Research Study
        link: github.com/demarkoLfulcher
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
             Conduct vulnerability research on a web based application that is integrated with a Large Language Mode. Prompt engineering on the LLM, how the web application handles a high number of requests, and if the web application was properly sand-boxed. Static analysis of the source code of the behind the Web infrastructure. Recorded findings and results in a research paper and presentations.
            


      - layout: top-middle
        title: Malware Analysis / Reverse Engineering of APK Samples 
        link: github.com/demarkoLfulcher
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
           De-compile and reverse engineering apk malware samples in order to understand how they work and for the ransomware samples determine if file retrieval is possible. I used Ghidra, apktools, waydroid, and gdb to conduct this research. The research included static and dynamic analysis of apk malware samples and a paper to document the findings and results.
      - layout: top-middle
        title: S - DES Implementation and MITM Attack 
        link: github.com/demarkoLfulcher
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs

      - layout: top-middle
        title: Formal-Methods of Post-Quantum Symmetric Key Agreement Protocol
        link: github.com/demarkoLfulcher
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
            
  - title: Experience  # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Building STEPS
        caption: 7/2022 - 8/2022
        sub_title: General Tutor
        quote: >
          Developed by a science consultant to help under-represented students become science and technology professionals, Building STEPS increases the number of students who earn a college degree and enter STEM and healthcare careers. Launched in Baltimore in 2000, and partnering with our city’s more challenged, under-resourced public high schools, Building STEPS unlocks potential and propels high achieving, highly motivated students to college and career success.
        description: | # this will include new lines to allow paragraphs
          Provide individualized tutoring and academic support to under-represented high school students in science, technology, engineering, and mathematics (STEM) subjects, fostering academic growth and confidence. Develop and implement engaging lesson plans tailored to students' learning needs and goals, ensuring alignment with curriculum standards and Building STEPS' mission. Mentor and guide students through the college application process, including essay writing, test preparation, and identifying suitable higher education institutions and career paths. Collaborate with educators, counselors, and parents to track student progress, address academic challenges, and celebrate achievements. Organize and lead supplemental enrichment activities and workshops designed to enhance students’ understanding of STEM concepts and career opportunities. Contribute to Building STEPS' goal of increasing college degree attainment and career success among high-achieving, motivated students from under-resourced schools.          
      - layout: left
        title: AI4ALL
        caption: 7/2024 - 9/2024
        sub_title: Student Coordinator
        quote: >
          AI4ALL is a US-based nonprofit dedicated to increasing diversity and inclusion in AI education, research, development, and policy. As of December 2022, AI4ALL has impacted over 10,000 people in all 50 states and around the world through our programs.
        description: | # this will include new lines to allow paragraphs
          I have experience facilitating and assisting with AI4ALL Ignite Career Readiness events, specifically in conducting Resume and LinkedIn reviews, as well as participating in Opportunity Chats aimed at recruitment. I regularly held periodic check-in meetings with staff and fellow student coordinators to ensure smooth coordination and communication throughout programs. Additionally, I actively participated in debriefing meetings following the conclusion of AI4ALL Ignite Career Readiness programs to evaluate outcomes and identify areas for improvement. I provided administrative support for 2-3 AI4ALL Ignite Career Readiness classes, which included managing student communications, documenting assignments, and tracking attendance. I also gained proficiency in Salesforce by documenting student internship experiences across various AI4ALL programs. Furthermore, I effectively managed projects and tasks using the Asana work management platform, demonstrating strong organizational skills and attention to detail in project execution.


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Maryland Baltimore County
        caption: 2020 - 2025
        sub_title: B.A. Matematics 
        quote: >
          The University of Maryland, Baltimore County (UMBC), founded in 1966, is a public research university located in Baltimore County, Maryland. It was established as part of the University System of Maryland and has since grown into a prominent institution known for its excellence in education and research.
        description: | # this will include new lines to allow paragraphs
          During my pursuit of dual degrees in Mathematics and Statistics at the University of Maryland Baltimore County, I developed crucial skills that have greatly influenced my career, particularly in teamwork and managing tight deadlines. My academic journey was highly enriching, offering me valuable insights into maintaining a balanced work-life dynamic. Beyond my studies, I invested significant time serving on various club committees, including roles such as Event Coordinator and Treasurer for the UMBC Astronomy Club. These experiences were pivotal in refining my leadership capabilities and financial management skills.
  - title: Technical Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
     <p align="center"> <a href="https://www.cprogramming.com/" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/c/c-original.svg" alt="c" width="40" height="40"/> </a> <a href="https://www.w3schools.com/cpp/" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/cplusplus/cplusplus-original.svg" alt="cplusplus" width="40" height="40"/> </a> <a href="https://git-scm.com/" target="_blank" rel="noreferrer"> <img src="https://www.vectorlogo.zone/logos/git-scm/git-scm-icon.svg" alt="git" width="40" height="40"/> </a> <a href="https://www.haskell.org/" target="_blank" rel="noreferrer"> <img src="https://upload.wikimedia.org/wikipedia/commons/1/1c/Haskell-Logo.svg" alt="haskell" width="40" height="40"/> </a> <a href="https://www.linux.org/" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/linux/linux-original.svg" alt="linux" width="40" height="40"/> </a> <a href="https://pandas.pydata.org/" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/2ae2a900d2f041da66e950e4d48052658d850630/icons/pandas/pandas-original.svg" alt="pandas" width="40" height="40"/> </a> <a href="https://www.python.org" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/python/python-original.svg" alt="python" width="40" height="40"/> </a> <a href="https://scikit-learn.org/" target="_blank" rel="noreferrer"> <img src="https://upload.wikimedia.org/wikipedia/commons/0/05/Scikit_learn_logo_small.svg" alt="scikit_learn" width="40" height="40"/> </a> <a href="https://www.tensorflow.org" target="_blank" rel="noreferrer"> <img src="https://www.vectorlogo.zone/logos/tensorflow/tensorflow-icon.svg" alt="tensorflow" width="40" height="40"/> </a> </p>

      

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
